### ISSUE TITLE
RSL issue

### ISSUE THREAD

**Issue by sunt05** [UMEP-dev/SUEWS#106]
I did the first and i have the problem with temperature again 
this is the calculated from suews values
![image](https://user-images.githubusercontent.com/61833032/168447182-824cd7a1-d414-4c30-b1a7-00a2373bfb94.png)

the map to see in some areas the problem
![image](https://user-images.githubusercontent.com/61833032/168447213-d05651fc-1082-4f8a-91bb-43dcb2fd0047.png)
my data
[SUEWS_Soil.zip](https://github.com/UMEP-dev/UMEP/files/8693803/SUEWS_Soil.zip)

__Originally posted by @Empanag in https://github.com/UMEP-dev/UMEP/issues/415#issuecomment-1126806464__

**Comment by sunt05** [comment]
> any news about the issue?

Please update supy: `pip install supy==2022.7.1.dev0`, these issues should be resolved in this version; otherwise, please post here with your testing files.
Also, you can just include those grids with issues; other grids are not needed - they actually make our debugging much harder - thanks!

**Comment by Empanag** [comment]
> > any news about the issue?
> 
> Hi @Empanag,
> 
> Please update supy: `pip install supy==2022.7.1.dev0`, these issues should be resolved in this version; otherwise, please post here with your testing files. Also, you can just include those grids with issues; other grids are not needed - they actually make our debugging much harder - thanks!

Noted. 
i need SPARTACUS.nml. What is this?

**Comment by Empanag** [comment]
> Sorry to see this - the `dev` version of supy involves some changes in the input files - hence the `SPARTACUS.nml` file you noted. What is the setting for your `netradiationmethod`? if larger than 1000, please deduct it by 1000 (e.g. 1003 -> 3) and see if it works. otherwise, please see [here](https://github.com/UMEP-dev/SUEWS/tree/master/Test/BaseRun/2021a/Input) for example input files.

okey i will try to reproduce the input files from UMEP and contact you again.

**Comment by suegrimmond** [comment]
you shouldn't be using Spartacus at this time - it is not ready to be used yet

**Comment by Empanag** [comment]
Okey i downloaded the 'SUEWS_SPARTACUS.nml

> based on the error above, you just need to download the `SUEWS_SPARTACUS.nml` from [this place](https://github.com/UMEP-dev/SUEWS/tree/master/Test/BaseRun/2021a/Input) and place it in your input location (E:\SUEWSapp\testirrig\7-ir-25sm10-11-12-13). hope it will be resolved.

Okey i downloaded `SUEWS_SPARTACUS.nml` and also `GridLayout.nml` needed so i downloaded.

i have the following message but seems to run 

2020-08-01 23:00:00
2022-07-07 17:37:51,589 - SuPy - INFO - All cache cleared.
n_vegetation_region_urban 1 <class 'numpy.int32'> is not included: this should not happen! please report to the developer: https://github.com/UMEP-dev/SuPy/issues/new
n_stream_sw_urban 4 <class 'numpy.int32'> is not included: this should not happen! please report to the developer: https://github.com/UMEP-dev/SuPy/issues/new
n_stream_lw_urban 4 <class 'numpy.int32'> is not included: this should not happen! please report to the developer: https://github.com/UMEP-dev/SuPy/issues/new
2022-07-07 17:40:06,322 - SuPy - INFO - All cache cleared.
n_vegetation_region_urban 1 <class 'numpy.int32'> is not included: this should not happen! please report to the developer: https://github.com/UMEP-dev/SuPy/issues/new
n_stream_sw_urban 4 <class 'numpy.int32'> is not included: this should not happen! please report to the developer: https://github.com/UMEP-dev/SuPy/issues/new
n_stream_lw_urban 4 <class 'numpy.int32'> is not included: this should not happen! please report to the developer: https://github.com/UMEP-dev/SuPy/issues/new
2022-07-07 17:42:20,762 - SuPy - INFO - ====================
2022-07-07 17:42:20,763 - SuPy - INFO - Simulation period:
2022-07-07 17:42:20,764 - SuPy - INFO -   Start: 2020-08-01 02:05:00
2022-07-07 17:42:20,764 - SuPy - INFO -   End: 2020-08-02 02:00:00
2022-07-07 17:42:20,765 - SuPy - INFO - 
2022-07-07 17:42:20,766 - SuPy - INFO - No. of grids: 8976
2022-07-07 17:42:20,766 - SuPy - INFO - SuPy is running in serial mode

**Comment by sunt05** [comment]
@Empanag have you got the new version running? if not, please leave your input dataset here and I'll have a look recently.

**Comment by Empanag** [comment]
Hi Ting, i tried some runs and i have this error

```
2022-07-29 11:34:06,148 - SuPy - INFO - All cache cleared.
2022-07-29 11:34:06,148 - SuPy - ERROR - E:\SUEWSapp\testirrig\7-ir-25sm9-10-11-12\SUEWS_SPARTACUS.nml does not exists!
Traceback (most recent call last):
  File "C:\Users\RSLab20Emm\AppData\Local\Programs\Python\Python39\lib\site-packages\supy\_load.py", line 245, in load_SUEWS_nml
    df_nml = pd.DataFrame(parser.read(p_nml))
  File "C:\Users\RSLab20Emm\AppData\Roaming\Python\Python39\site-packages\f90nml\parser.py", line 279, in read
    nml_file = open(nml_fname, 'r') if nml_is_path else nml_fname
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\SUEWSapp\\testirrig\\7-ir-25sm9-10-11-12\\SUEWS_SPARTACUS.nml'
Traceback (most recent call last):
  File "E:\SUEWSapp\testirrig\7-ir-25sm9-10-11-12\suews.py", line 639, in <module>
    suews_out=suews(filefolder)
  File "E:\SUEWSapp\testirrig\7-ir-25sm9-10-11-12\suews.py", line 445, in suews
    df_state_init = sp.init_supy(path_runcontrol)
  File "C:\Users\RSLab20Emm\AppData\Local\Programs\Python\Python39\lib\site-packages\supy\_supy_module.py", line 103, in init_supy
    df_state_init = load_InitialCond_grid_df(
  File "C:\Users\RSLab20Emm\AppData\Local\Programs\Python\Python39\lib\site-packages\supy\_load.py", line 1751, in load_InitialCond_grid_df
    df_init = load_SUEWS_InitialCond_df(path_runcontrol)
  File "C:\Users\RSLab20Emm\AppData\Local\Programs\Python\Python39\lib\site-packages\supy\_load.py", line 1365, in load_SUEWS_InitialCond_df
    dict_ModConfig = load_SUEWS_dict_ModConfig(path_runcontrol)
  File "C:\Users\RSLab20Emm\AppData\Local\Programs\Python\Python39\lib\site-packages\supy\_load.py", line 1281, in load_SUEWS_dict_ModConfig
    dict_RunControl_x = {k[0]: v for k, v in load_SUEWS_nml(path_spartacus).items()}
AttributeError: 'NoneType' object has no attribute 'items'
```

**Comment by sunt05** [comment]
Did you place the Spartacus.nml file in that directory?

**Comment by Empanag** [comment]
yes i placed it, the previous comment didn't have the right error this is the real one with SUEWS_spartacus.nml and GridLayout.nml
```
2020-06-05 23:00:00                                                      ]   0%
2022-07-29 14:30:27,886 - SuPy - INFO - All cache cleared.
2022-07-29 14:30:27,886 - SuPy - ERROR - E:\SUEWSapp\testirrig\7-ir-25sm9-10-11-12\SUEWS_SPARTACUS.nml does not exists!
Traceback (most recent call last):
  File "C:\Users\RSLab20Emm\AppData\Local\Programs\Python\Python39\lib\site-packages\supy\_load.py", line 245, in load_SUEWS_nml
    df_nml = pd.DataFrame(parser.read(p_nml))
  File "C:\Users\RSLab20Emm\AppData\Roaming\Python\Python39\site-packages\f90nml\parser.py", line 279, in read
    nml_file = open(nml_fname, 'r') if nml_is_path else nml_fname
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\SUEWSapp\\testirrig\\7-ir-25sm9-10-11-12\\SUEWS_SPARTACUS.nml'
Traceback (most recent call last):
  File "E:\SUEWSapp\testirrig\7-ir-25sm10-11-12-13\suews.py", line 639, in <module>
    suews_out=suews(filefolder)
  File "E:\SUEWSapp\testirrig\7-ir-25sm10-11-12-13\suews.py", line 445, in suews
    df_state_init = sp.init_supy(path_runcontrol)
  File "C:\Users\RSLab20Emm\AppData\Local\Programs\Python\Python39\lib\site-packages\supy\_supy_module.py", line 103, in init_supy
    df_state_init = load_InitialCond_grid_df(
  File "C:\Users\RSLab20Emm\AppData\Local\Programs\Python\Python39\lib\site-packages\supy\_load.py", line 1751, in load_InitialCond_grid_df
    df_init = load_SUEWS_InitialCond_df(path_runcontrol)
  File "C:\Users\RSLab20Emm\AppData\Local\Programs\Python\Python39\lib\site-packages\supy\_load.py", line 1365, in load_SUEWS_InitialCond_df
    dict_ModConfig = load_SUEWS_dict_ModConfig(path_runcontrol)
  File "C:\Users\RSLab20Emm\AppData\Local\Programs\Python\Python39\lib\site-packages\supy\_load.py", line 1281, in load_SUEWS_dict_ModConfig
    dict_RunControl_x = {k[0]: v for k, v in load_SUEWS_nml(path_spartacus).items()}
AttributeError: 'NoneType' object has no attribute 'items'
```

**Comment by sunt05** [comment]
Please zip the whole folder and post it here - I'll have a look later on today.

**Comment by Empanag** [comment]
[7-ir-25sm10-11-12-13.zip](https://github.com/UMEP-dev/SUEWS/files/9221035/7-ir-25sm10-11-12-13.zip)

you can run the code inside by changing the line 591 to the folder that all of these are exported.

**Comment by sunt05** [comment]
I just had a try -  the issue is in your `suews.py` file, in which the `filefolder` in line 624 overrides the same variable set in line 591.

And if you notice the line in the error message above - 

```
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\SUEWSapp\\testirrig\\7-ir-25sm9-10-11-12\\SUEWS_SPARTACUS.nml'
```

you might have got the clue.

**Comment by Empanag** [comment]
yes you are right for this. I change it and now i have this error. (everything is the same except the 624 line that i erased it)

```
Traceback (most recent call last):
  File "C:\Users\RSLab20Emm\AppData\Local\Programs\Python\Python39\lib\site-packages\supy\_run.py", line 368, in run_supy_ser
    list_res = [
  File "C:\Users\RSLab20Emm\AppData\Local\Programs\Python\Python39\lib\site-packages\supy\_run.py", line 369, in <listcomp>
    suews_cal_tstep_multi(dict_input_grid, df_forcing)
  File "C:\Users\RSLab20Emm\AppData\Local\Programs\Python\Python39\lib\site-packages\supy\_run.py", line 116, in suews_cal_tstep_multi
    dict_input = {k: dict_input[k] for k in list_var_input_multitsteps}
  File "C:\Users\RSLab20Emm\AppData\Local\Programs\Python\Python39\lib\site-packages\supy\_run.py", line 116, in <dictcomp>
    dict_input = {k: dict_input[k] for k in list_var_input_multitsteps}
KeyError: 'n_vegetation_region_urban'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\SUEWSapp\testirrig\7-ir-25sm10-11-12-13\suews.py", line 639, in <module>
    suews_out=suews(filefolder)
  File "E:\SUEWSapp\testirrig\7-ir-25sm10-11-12-13\suews.py", line 453, in suews
    df_output,df_state_final=sp.run_supy(df_forcing,df_state_init,chunk_day=1)
  File "C:\Users\RSLab20Emm\AppData\Local\Programs\Python\Python39\lib\site-packages\supy\_supy_module.py", line 370, in run_supy
    df_output, df_state_final = run_supy_ser(
  File "C:\Users\RSLab20Emm\AppData\Local\Programs\Python\Python39\lib\site-packages\supy\_run.py", line 375, in run_supy_ser
    raise RuntimeError("SUEWS kernel error")
RuntimeError: SUEWS kernel error
```

**Comment by sunt05** [comment]
Hopefully, my answer above addresses this issue, so I'll close it for now. Otherwise, feel free to re-open and provide more details to help resolve it.
