### ISSUE TITLE
SuPy Could not run with diagmethod error

### ISSUE THREAD

**Issue by phemiobe** [UMEP-dev/SUEWS#169]
Hello, 
I tried to run SuPy but I encounter the following error. I don't know what actually this means

My SuPy version is 
Name: supy
Version: 2022.9.22
 

File "/home/people/20202815/.local/lib/python3.8/site-packages/supy/_run.py", line 117, in <dictcomp>
    dict_input = {k: dict_input[k] for k in list_var_input_multitsteps}
KeyError: 'diagmethod'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/people/20202815/.local/lib/python3.8/site-packages/multiprocess/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/people/20202815/.local/lib/python3.8/site-packages/multiprocess/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/people/20202815/.local/lib/python3.8/site-packages/supy/_run.py", line 431, in run_save_supy
    df_output, df_state_final = run_supy_ser(
  File "/home/people/20202815/.local/lib/python3.8/site-packages/supy/_run.py", line 384, in run_supy_ser
    path_zip_debug = save_zip_debug(df_forcing, df_state_init)
  File "/home/people/20202815/.local/lib/python3.8/site-packages/supy/util/_debug.py", line 198, in save_zip_debug
    show_version(as_json=path_json_version.as_posix())
  File "/home/people/20202815/.local/lib/python3.8/site-packages/supy/_version.py", line 45, in show_version
    ser_json = pd.read_json(path_json, typ="series", convert_dates=False)
  File "/home/people/20202815/.local/lib/python3.8/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/home/people/20202815/.local/lib/python3.8/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/home/people/20202815/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 757, in read_json
    return json_reader.read()
  File "/home/people/20202815/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 915, in read
    obj = self._get_object_parser(self.data)
  File "/home/people/20202815/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 942, in _get_object_parser
    obj = SeriesParser(json, **kwargs).parse()
  File "/home/people/20202815/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 1064, in parse
    self._parse_no_numpy()
  File "/home/people/20202815/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 1229, in _parse_no_numpy
    data = loads(self.json, precise_float=self.precise_float)
ValueError: Expected object or value

**Comment by sunt05** [comment]
How was your `df_state` generated?

**Comment by phemiobe** [comment]
Thanks for this Sunt05.
The input for SuPy was actually generated with the SUEWS prepare (UMEP)-see the attached file. and the following code was used to run SuPy:
import supy as sp
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from pathlib import Path
#ar=np.full((105118,573),np.pi)
path_runcontrol = Path('/home/people/20202815/scratch/SUEWS_Dublin/') / 'RunControl.nml'
df_state_init = sp.init_supy(path_runcontrol)
grid = df_state_init.index[0]
df_forcing = sp.load_forcing_grid(path_runcontrol, grid)
df_output, df_state_final = sp.run_supy(df_forcing, df_state_init)
list_path_save = sp.save_supy(df_output, df_state_final, freq_s=3600, site='', path_dir_save='/home/people/20202815/scratch/SUEWS_Dublin/output')

the RunControl.nml file describes the physics and the path to the Suews input file.  However, a column is now missing in the df_state for this latest version and the model could not run...


[SUEWS_input.zip](https://github.com/UMEP-dev/SUEWS/files/11026997/SUEWS_input.zip)

**Comment by phemiobe** [comment]
This was solved when I added the diagmethod line in the Runcontrol file as indicated here. many thanks for your contribution

**Comment by sunt05** [comment]
Excellent!
